# Generated by Django 4.2.9 on 2024-03-31 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SupportReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=50, null=True)),
                ('friendly_reason', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': "Support Reason's",
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('driving_school', models.TextField(blank=True, max_length=25, null=True)),
                ('text_field', models.TextField()),
                ('reason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='message_center.supportreason')),
            ],
            options={
                'verbose_name': 'Support Message',
                'verbose_name_plural': "Support Message's",
            },
        ),
    ]
