# Generated by Django 4.2.9 on 2024-03-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_center', '0002_alter_support_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportreason',
            options={'verbose_name_plural': "Support Reason's"},
        ),
        migrations.AddField(
            model_name='support',
            name='driving_school',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
