# Generated by Django 4.2.9 on 2024-03-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_center', '0003_alter_supportreason_options_support_driving_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='driving_school',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
    ]
