# Generated by Django 4.2.9 on 2024-03-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessontypes',
            options={'verbose_name': 'Lesson Type', 'verbose_name_plural': "Lesson Type's"},
        ),
        migrations.RemoveField(
            model_name='drivingschool',
            name='instructors',
        ),
        migrations.RemoveField(
            model_name='drivingschool',
            name='students',
        ),
        migrations.RemoveField(
            model_name='drivingschool',
            name='subscription_plan',
        ),
    ]
