# Generated by Django 4.2.9 on 2024-03-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driving_school', '0002_alter_lessontypes_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivingschool',
            name='lesson_types',
        ),
        migrations.AlterField(
            model_name='drivingschool',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
