# Generated by Django 4.2.9 on 2024-03-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_instructor_owner_student_studentprofile_ownerprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructorprofile',
            name='instructor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='owner_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
