# Generated by Django 4.2.9 on 2024-03-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_delete_instructor_delete_owner_delete_student_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='instructor_id',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_id',
        ),
    ]
